spring.application.name=mcp-shorten-url

# Logging configuration
logging.level.root=INFO
logging.level.com.kerry.mcpshortenurl=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
